# -*- coding: utf-8 -*-
"""hebbian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sRfqmWwPD-wv3fE-TzzncSb4DHAcPwyY
"""

def hebbian_learning(samples):
    print(f'{"Input":^10} {"T":^3} {"ΔW":^17} {"Weights":^25}')
    w1 = w2 = b = 0
    print(' ' * 35, f'({w1:4},{w2:4},{b:4})')
    for x1, x2, y in samples:
        dw1, dw2, db = x1 * y, x2 * y, y
        w1 += dw1
        w2 += dw2
        b += db
        print(f'({x1:2},{x2:2}) {y:2}   ({dw1:4},{dw2:4},{db:4})   ({w1:4},{w2:4},{b:4})')

samples = {
    'binary_bin':    [[1, 1, 1], [1, 0, 0], [0, 1, 0], [0, 0, 0]],
    'binary_bip':    [[1, 1, 1], [1, 0, -1], [0, 1, -1], [0, 0, -1]],
    'bipolar_bip':   [[1, 1, 1], [1, -1, -1], [-1, 1, -1], [-1, -1, -1]]
}

print('\nAND - Binary Input, Binary Output')
hebbian_learning(samples['binary_bin'])

print('\nAND - Binary Input, Bipolar Output')
hebbian_learning(samples['binary_bip'])

print('\nAND - Bipolar Input, Bipolar Output')
hebbian_learning(samples['bipolar_bip'])