# -*- coding: utf-8 -*-
"""linreg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jlVa2fKcx-R7TPexpTYrQyAxzWUVwPrV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

data = {
    'Hours': [1, 2, 3, 4.5, 5, 6.5, 7, 8.5, 9, 10],
    'Scores': [20, 25, 35, 50, 52, 60, 62, 75, 85, 95]
}

df = pd.DataFrame(data)

X = df[['Hours']]
y = df['Scores']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(results)

plt.scatter(X, y, color='blue', label='Actual Data')
plt.plot(X, model.predict(X), color='red', label='Regression Line')
plt.title('Hours vs Score')
plt.xlabel('Hours Studied')
plt.ylabel('Score')
plt.legend()
plt.grid(True)
plt.show()